### PR TITLE
fix case-insensitive import collision

### PR DESCRIPTION
**Pull request by lizhengqiang**
fix case-insensitive import collision

### CODE REVIEW

**Comment by Krystian19** [comment]
@unknwon Please accept this change, i'm getting installation errors because of it.

**Comment by unknwon** [comment]
This change alone won’t solve the problem I think, I need to roll back some changes regarding Go mod name.

**Comment by unknwon** [comment]
Since my GitHub handle converted to lower case for long-term purpose. And research a lot on other repos faced similar issue, I think this is a must have step to forward on updating import path.

If you're getting errors on a specific package, just ping me and I'll send out PR to those repos.

**Comment by Krystian19** [comment]
@unknwon I'm getting an error while installing [https://github.com/Unknwon/bra](url)

```sh
```

**Comment by unknwon** [comment]
@Krystian19 thanks! Updating it.

**Comment by unknwon** [comment]
@Krystian19 updated, would you mind try again? `go get github.com/unknwon/bra`

**Comment by Krystian19** [comment]
@unknwon It works like a charm, Thank you !!

Great job with [Bra](https://github.com/Unknwon/bra) BTW, it's the best one i've found.

**Comment by unknwon** [comment]
@Krystian19 no problem, my pleasure :D

@lizhengqiang which package you're trying to download/install? I can send out PRs as well.

**Comment by lizhengqiang** [comment]
123Step 32/76 : RUN go get github.com/go-macaron/cache
124 ---> Running in 34955ce7ad0f
125package github.com/Unknwon/com: case-insensitive import collision: "github.com/Unknwon/com" and "github.com/unknwon/com"

**Comment by unknwon** [comment]
@lizhengqiang thanks, fixed!

**Pull request closed without merging**
